### ISSUE TITLE
Fake nudes for celebrities?

### ISSUE THREAD

**Issue by vlainic** [daviddao/awful-ai#50]
Hello. Is [this ](https://www.forbes.com/sites/siladityaray/2020/10/20/bot-generated-fake-nudes-of-over-100000-women-without-their-knowledge-says-report/) included? I just see this [one](https://www.theverge.com/2019/6/27/18760896/deepfake-nude-ai-app-women-deepnude-non-consensual-pornography)

**Comment by PoorPocketsMcNewHold** [comment]
I can also add that one, having expended to underage girls. https://www.dailymail.co.uk/sciencetech/article-8863233/Disturbing-deepfake-tool-popular-messaging-app-Telegram-forging-NUDE-images-underage-girls.html
This doesn’t apply to celebrities exclusively, due to methods of creating deepfakes, more and more easy to have access too.

**Comment by hugopilot** [comment]
Both uses are probably based on the DeepNude/DreamPower algo. It has been added in PR #47
